### PR TITLE
Changed eFP and rFP for ammo weapons

### LINKED ISSUE #775: SRMs reported with different eFP and rFP,  in the weapons page.
**LSML version:** 2.0.14
**Screen resolution:** 3440x1440
**Java version:** 8u333

**Steps to reproduce issue:**
1. Open LSML
2. Click on weapons page/tab
3. compare eFP with rFP on the SRMs (or any other single volley missile)

**Actual result:**
eFP and rFP have different values.

**Expected result:**
because they are a single volley they should have the same value.

### PR DESCRIPTION
**Pull request by sestrand**
Adjusted eFP and rFP for ammo weapons.  Added reading the PGI files for volleysize and used that value where appropriate.  this now correctly calculates eFP and rFP for volley weapons (particularly missiles) and fixes issue #775.  And changed the name of the getAmmoPerPerShot to getRoundsPerShot which more exactly explains what it is doing.

### CODE REVIEW

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java [hunk 1]
```diff
@@ -63,6 +67,10 @@ public AmmoWeapon(
               aRangeProfile, aRoundsPerShot, aDamagePerProjectile, aProjectilesPerRound, aProjectileSpeed,
               aGhostHeatGroupId, aGhostHeatMultiplier, aGhostHeatMaxFreeAlpha, aVolleyDelay, aImpulse);
         ammoTypeId = aAmmoType;
+        // protect from bad values
+        if (aVolleySize < 1) { volleysize = aRoundsPerShot; } else { volleysize = aVolleySize; }
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: Could you please put this on separate lines or use a ternary statement to assign volleysize?

The style for if-else-statements in LSML is to always use brackets (which you do) and use new lines after opening bracket. Unless doing so would produce excessively long code (e.g. a very long chanin of if-else statements that cannot be replaced with a switch-case).

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java [hunk 2]
```diff
@@ -45,16 +45,20 @@ public class AmmoWeapon extends Weapon {
     @XStreamAsAttribute
     private final String ammoTypeId;
     @XStreamAsAttribute
+    private final int volleysize;
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: Can you capitalize the S in size so that the naming is consistent with the rest of the file please? LSML uses camelCase with first word being lowercase.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java [hunk 3]
```diff
@@ -81,19 +89,48 @@ public Ammunition getAmmoType() {
...
+     /**
+     * The unmodified time between shots. C.f. {@link #getExpectedFiringPeriod(Collection)}.
+     * <p>
+     * Note that this is different from cooldown which is the time the weapon is unavailable between uses, this is
+     * the time between activations of the weapon. In particular this includes the time that it takes to charge
+     * a gauss rifle, the burn time of lasers, the volley delay from LRMs etc that is not included in cooldown.
+     *
+     * @return The firing period [seconds]
+     * @param aModifiers The modifiers to apply from quirks etc.
+     * there can also be additional delay for hardpoint volley size limitations. not accounted for, yet.
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: No free text after the parameter list please.  Also I think this is from the base class comment right? If so can you please use `@inheritDoc` instead of copying the documentation? That way we reduce the risk of the copied docs not being updated when base doc changes (I didn't know this existed for the longest time during LSML development so I've incorrectly used `@see` or `@link` instead and I intend to fix this as I go along).

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java [hunk 4]
```diff
@@ -81,19 +89,48 @@ public Ammunition getAmmoType() {
...
+     */
     @Override
-    public double getExpectedFiringPeriod(Collection<Modifier> aModifiers) {
-        return isOneShot() ? Double.POSITIVE_INFINITY : super.getExpectedFiringPeriod(aModifiers);
-    }
+    public double getRawFiringPeriod(Collection<Modifier> aModifiers) {
+        int numRoundsPerShot = super.getRoundsPerShot();
+        int volleySize = volleysize;
+        if (volleySize < 1) {
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: I'd rather just leave this out since you've added the code to make sure that volleySize is positive non-zero in the parsing. In general we trust the database file to be correct and want errors to be loud, so we can find and fix, but not crashing so we lose data. There's a top level exception handler that for most situation prevents LSML from crashing when exceptions are thrown and allows the user to safely exit the program and save their garage.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java [hunk 5]
```diff
@@ -81,19 +89,48 @@ public Ammunition getAmmoType() {
...
+            // This is just to fix this if someting went wrong.  probably should through an exception of some sort.
+            volleySize = numRoundsPerShot;
+        }
+        double numVolleys = Math.ceil(numRoundsPerShot / volleySize);
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: This doesn't do what you want. Both the operands are `int` so the truncation happens before the ceil operator so the ceil operator will never do anything here. You need to convert at least one of the operands to `double` before the division to prevent the truncation. I'd recommend adding a test to catch this bug.

File: src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java [hunk 6]
```diff
@@ -73,7 +73,7 @@ public BallisticWeapon(
               // HeatSource Arguments
               aHeat,
               // Weapon Arguments
-              aCooldown, aRangeProfile, aRoundsPerShot, aDamagePerProjectile, aProjectilesPerRound, aProjectileSpeed,
+              aCooldown, aRangeProfile, aRoundsPerShot, aRoundsPerShot, aDamagePerProjectile, aProjectilesPerRound, aProjectileSpeed,
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java]: I think this doesn't compile? xD

File: src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java [hunk 7]
```diff
@@ -90,6 +90,7 @@ public BallisticWeapon(
     }
 
     public boolean canDoubleFire() {
+        // this is not the true definition for this value, and while currently only 1 for those that can fire mduring cooldown, that may not always be the case.
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java:93]: I struggled parsing this, was 1 meant to be true? Please use capital letter at the start of a sentence to be consistent with the rest of the code base.

File: src/main/java/org/lisoft/lsml/model/item/Weapon.java [hunk 8]
```diff
@@ -61,12 +61,13 @@ public class Weapon extends HeatSource {
     private final int projectilesPerRound;
     private final WeaponRangeProfile rangeProfile;
     /**
-     * How many rounds of ammo per shot of the weapon.
+     * How many rounds and how fast are they fired per shot of the weapon.
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/Weapon.java:64]: What do you mean with "how fast"? I don't think that this variable has anything to do with projectile speed or rate of fire?

File: src/main/java/org/lisoft/lsml/model/item/Weapon.java [hunk 9]
```diff
@@ -104,9 +105,12 @@ public Collection<String> getAliases() {
         return Collections.unmodifiableCollection(coolDown.getSelectors());
     }
 
-    public int getAmmoPerPerShot() {
+    public int getRoundsPerShot() {
         return roundsPerShot;
     }
+    public double getVolleyDelay() {
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/Weapon.java]: Missing newline.

File: src/main/java/org/lisoft/lsml/model/item/Weapon.java [hunk 10]
```diff
@@ -129,7 +133,10 @@ public double getDamagePerShot() {
 
     /**
      * The statistically expected time between shots accounting for weapon jams and double fire etc.
-     *
+     * @param aModifiers The modifiers to apply from quirks etc.
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/Weapon.java:132]: `@param` always before `@return` and no free text after either of them please.

File: src/main/java/org/lisoft/lsml/model/item/Weapon.java [hunk 11]
```diff
@@ -190,11 +197,17 @@ public WeaponRangeProfile getRangeProfile() {
      * Note that this is different from cooldown which is the time the weapon is unavailable between uses, this is
      * the time between activations of the weapon. In particular this includes the time that it takes to charge
      * a gauss rifle, the burn time of lasers, the volley delay from LRMs etc that is not included in cooldown.
+     * 
+     * ammoweapons and energy weaspons calculate this differently. So this is an overridden method.
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/Weapon.java]: Please use full sentences and check spelling. If you refer to another class, prefer to `@link` it for easier navigation.

The override section can be read as ambigous and mean that this method overrides, which is false. I'd express this more clearly as "this method is overridden by some subclasses"

File: src/main/java/org/lisoft/lsml/model/item/Weapon.java [hunk 12]
```diff
@@ -61,12 +61,13 @@ public class Weapon extends HeatSource {
     private final int projectilesPerRound;
     private final WeaponRangeProfile rangeProfile;
     /**
-     * How many rounds of ammo per shot of the weapon.
+     * How many rounds and how fast are they fired per shot of the weapon.
      */
     @XStreamAsAttribute
     private final int roundsPerShot;
     @XStreamAsAttribute
     private final double volleyDelay;
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/Weapon.java]: Since this is no longer used in the base class, can you push it out to AmmoWeapon where it can live together with the related volleySize attribute?

File: src/main/java/org/lisoft/lsml/model/item/Weapon.java [hunk 13]
```diff
@@ -190,11 +197,17 @@ public WeaponRangeProfile getRangeProfile() {
...
+     * 
+     * ammoweapons and energy weaspons calculate this differently. So this is an overridden method.
      *
      * @return The firing period [seconds]
+     * @param aModifiers The modifiers to apply from quirks etc.
+     * there can also be additional delay for hardpoint volley size limitations. not accounted for, yet.
      */
     public double getRawFiringPeriod(Collection<Modifier> aModifiers) {
-        return getCoolDown(aModifiers) + volleyDelay * (roundsPerShot - 1);
+        double cooldown = getCoolDown(aModifiers);
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/Weapon.java:203]: `return getCoolDown(aModifiers);`.

File: src/test/java/org/lisoft/lsml/model/item/BallisticWeaponTest.java [hunk 14]
```diff
@@ -42,10 +42,10 @@ public void testCUAC10() throws Exception {
         final BallisticWeapon cut = (BallisticWeapon) ItemDB.lookup(1206);
 
         assertTrue(cut.getName().contains("C-ULTRA AC/10"));
-        assertEquals(3, cut.getAmmoPerPerShot());
+        assertEquals(3, cut.getRoundsPerShot());
         assertEquals(10.0, cut.getDamagePerShot(), 0.0001);
 
-        final double expectedSecondsPerShot = cut.getCoolDown(null) + 0.11 * 2;
```
Comment (LiSongMWO) [inline src/test/java/org/lisoft/lsml/model/item/BallisticWeaponTest.java:48]: I don't believe that removing this is correct. AFAIR the `volleydelay="0.11"` attribute from the data files applies between the rounds for C-UAC X.

File: src/test/java/org/lisoft/lsml/model/item/WeaponTest.java [hunk 15]
```diff
@@ -65,6 +65,7 @@ public void testConstruction() {
         final Attribute aCooldown = new Attribute(cooldown, selectors, ModifierDescription.SPEC_WEAPON_COOL_DOWN);
 
         final int aRoundsPerShot = 15;
+        final int aVolleySize = 1;
```
Comment (LiSongMWO) [inline src/test/java/org/lisoft/lsml/model/item/WeaponTest.java]: Seems to be unused?

File: src/test/java/org/lisoft/lsml/model/item/WeaponTest.java [hunk 16]
```diff
@@ -96,13 +97,13 @@ public void testConstruction() {
...
         assertSame(aRangeProfile, cut.getRangeProfile());
 
-        assertEquals(aRoundsPerShot, cut.getAmmoPerPerShot());
+        assertEquals(aRoundsPerShot, cut.getRoundsPerShot());
         assertEquals(aDamagePerProjectile * aProjectilesPerRound * aRoundsPerShot, cut.getDamagePerShot(), 0.0);
         assertEquals(projectileSpeed, cut.getProjectileSpeed(null), 0.0);
         assertEquals(aGhostHeatGroupId, cut.getGhostHeatGroup());
         assertEquals(aGhostHeatMultiplier, cut.getGhostHeatMultiplier(), 0.0);
         assertEquals(ghostHeatMaxFreeAlpha, cut.getGhostHeatMaxFreeAlpha(null));
-        assertEquals(cooldown + aVolleyDelay * (aRoundsPerShot - 1), cut.getExpectedFiringPeriod(null), 0.0);
```
Comment (LiSongMWO) [inline src/test/java/org/lisoft/lsml/model/item/WeaponTest.java:105]: Removing this is only correct if the ballistic volley delay computation is pushed from `Weapon` to `AmmoWeapon` in which case testing of that functionality needs to move as well.

File: src/test/java/org/lisoft/lsml/model/item/WeaponTest.java [hunk 17]
```diff
@@ -312,5 +313,29 @@ public void testRangeModifiers() throws Exception {
         final double expectedMaxRange = (llas.getRangeMax(null) + 100.0) * (1.0 + 0.1);
         assertEquals(expectedMaxRange, llas.getRangeMax(modifiers), 0.0);
     }
-
+    
+    @Test
+    public void testCheckExpectedDamage() throws Exception {
```
Comment (LiSongMWO) [inline src/test/java/org/lisoft/lsml/model/item/WeaponTest.java]: `testCheck` is redundant. Maybe "testRawExpectedFiringPeriodAllWeapons" ?

File: src/test/java/org/lisoft/lsml/model/item/WeaponTest.java [hunk 18]
```diff
@@ -312,5 +313,29 @@ public void testRangeModifiers() throws Exception {
...
+        final List<Weapon> weapons = ItemDB.lookup(Weapon.class);
+        double rFP, eFP;
```
Comment (LiSongMWO) [inline src/test/java/org/lisoft/lsml/model/item/WeaponTest.java]: Please try to always assign variables when created to reduce risk of using unitialized variables. These don't need to be here and can be defined when assigned below on lines 323 and 324.

File: src/test/java/org/lisoft/lsml/model/item/AmmoWeaponTest.java [hunk 19]
```diff
@@ -104,4 +104,15 @@ public final void testSpreadQuirks() throws Exception {
...
+    public void testGetVolleySize() throws Exception {
+        final AmmoWeapon ac20 = (AmmoWeapon) ItemDB.lookup("AC/20");
+        final AmmoWeapon lrm10 = (AmmoWeapon) ItemDB.lookup("LRM 10");
+        final AmmoWeapon clrm10 = (AmmoWeapon) ItemDB.lookup("C-LRM 10");
+        
+        assertEquals(10, lrm10.getVolleySize());
+        assertEquals(1, clrm10.getVolleySize());
+        assertEquals(1, ac20.getVolleySize());
+    }
 }
```
Comment (LiSongMWO) [inline src/test/java/org/lisoft/lsml/model/item/AmmoWeaponTest.java:133]: I think we should add a few more tests here to test the computation  with volleysize/delay in `getRawFiringPeriod` I currently only see tests that check if the parsing was done correctly.

**Comment by LiSongMWO** [comment]
There are some formatting things that I didn't comment on, does your IDE support loading the [formatter file that's provided for IntelliJ](https://github.com/lisongmechlab/lsml/blob/develop/intellij_code_style.xml)?

**Comment by sestrand** [comment]
No idea, but I'll give it a try.

**Comment by LiSongMWO** [comment]
I'm going to try to commit some time this coming week to finish the
remaining open issues and releanse 2.0.15. How are things looking on your
end? Do you think it would be possible to finish that bug during the next
week?

**Comment by sestrand** [comment]
As in, getting the format to match?  That has not been as easy as I had
hoped.  But I can try again tomorrow. In theory it should work, but I have
to set up two separate java instances (one new enough for the plug in and
the other that matches what lsml uses.).

The bug is otherwise fixed as far as I can tell.

**Comment by LiSongMWO** [comment]
Oh I see what happened now! I was waiting on you to respond to my review comments... However I forgot to hit submit on the review... Ooops, I did a dum xD

**Comment by sestrand** [comment]
regarding "No free text after the parameter list please. Also I think this
is from the base class comment right? If so can you please use @inheritDoc "
- I moved this from the base to here because it only applies to the
ammoweapon weapons.  so nothing to inherit.  but I can move the free text
prior.


regarding "I'd express this more clearly as "this method is overridden by
some subclasses"" . -  the truth is ... it is overridden by all
subclasses... and needs to be.  Is there a better way to define this method
to ensure that all subclasses override it?


regarding "I struggled parsing this, was 1 meant to be true? Please use
capital letter at the start of a sentence to be consistent with the rest of
the code base."  -  The value being parsed is not necessarily always a 1.
so "can double fire" should not be a boolean it should be a number of times
a weapon can fire before cooldown is complete.  PGI happens to have set
this as a 1 for all instances but the word used to create this does not
mean true or false.  I want to change the way lsml reads and
implements this value to stay consistent with the way PGI may use this
value. and change what this method is named to fix that potential problem.


regarding "Can you capitalize the S in size so that the naming is
consistent with the rest of the file please? LSML uses camelCase with first
word being lowercase."  - I agree that lsml code uses camelCase.  but when
parsing these files, I think LSML shoudl initially use the exact same name
and meaning and spelling and case as PGI source xml... to keep us from
getting confused.  There is more I want to change in LSML to get to that
start position.  PGI is not consistent in using camelCase in the XML.
certainly open to discuss, but it definitely makes it easier to see where
in teh code the pgi xml variables end up.


regarding "0.11 removal from  C-UAC X." when you pull the trigger during
cooldown, there is no additional time added to the cooldown for that
interim shot.  I went into the game and tested against my target self with
a stopwatch .  I don't find any additional time... interim shots cant fire
before .11 after the first shot, but the cooldown is just the cooldown from
completion of the first shot.


I'll clean up what I can in the next few days.

**Comment by LiSongMWO** [comment]
Could you use the threaded reply feature in the review UI please? That would keep the comment thread local to the code the comments are about, making it easier to reference the code in question :)

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 3 above)
Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: Sestrand said:  I moved this from the base to here because it only applies to the
ammoweapon weapons.  so nothing to inherit.  but I can move the free text
prior.

Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: The comment in Weapon.java hasn't been moved. There were a few lines added to it. 

What I'm asking for is something like this:

```
/**
 * {@inheritDoc}
 *
 * Also accounts for volley size of weapons that have such limitations.
 * 
 * @param aModifiers {@inheritDoc}
 * @return {@inheritDoc}
 * /
```

And then remove the mention of volley size in the base method javadoc because it doesn't actually do that. Or alternatively to keep the mention in the [base method](https://github.com/lisongmechlab/lsml/pull/778/files/7a9c2b454ddca52f15168c84ec938ef1ffad4c1b#diff-f210accc0fc5382ea421d7526373d66e1252c07ce4aed7ba951ce372884e73a1) and just use /** `{@inheritDoc}` */ here. Or leave the comment empty (the IDE would figure out the inheritance).

File: src/main/java/org/lisoft/lsml/model/item/Weapon.java (hunk 11 above)
Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/Weapon.java]: @Sestrand says: the truth is ... it is overridden by all
subclasses... and needs to be.  Is there a better way to define this method
to ensure that all subclasses override it?

Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/Weapon.java]: We can bikeshed about this if you'd like; what I'd like addressed is the clarity and value of the comment. I found that the comment was ambiguous from a language point of view and that it subjectively doesn't provide that much value, at least to me, because my IDE (intelliJ community) already renders the method as overridden. 

I see a few ways we could resolve this while keeping us both happy:

1. Make the class `abstract` and mark this method as `abstract` as well, this forces all inheriting, concrete classes to implement the method and makes it obvious to the reader what you're trying to say in the comment. This comes with the downside that this is a rather intrusive change that may entail changing some more code in unit test were `Weapon` objects might be instantiated directly for some tests etc and would need some manual testing to make sure nothing subtly breaks in the UI. There's no precedent for doing this in LSML and I don't know how the database format will deal with it, it might just be a nothing burger, it might also be a hair loss experience :)
2. Just remove the comment about the method being overridden, in Java one has to assume that this is generally a possibility unless the method is marked `final` but that forbids overriding which in and of itself is a bit of a problem as it prevents the method from being mocked in unit tests, see: https://github.com/mockito/mockito/wiki/FAQ.
3. Reword the comment to call attention to specific overriding methods using for example something like this: `Note that this behaviour is changed by inheriting classes. See also: {@see MissileWeapon#getRawFiringPeriod}, ...`.

File: src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java (hunk 7 above)
Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java:93]: @sestrand said: The value being parsed is not necessarily always a 1. so "can double fire" should not be a boolean it should be a number of times a weapon can fire before cooldown is complete.  PGI happens to have set this as a 1 for all instances but the word used to create this does not mean true or false.  I want to change the way lsml reads and implements this value to stay consistent with the way PGI may use this value. and change what this method is named to fix that potential problem.

Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java:93]: I see what you're trying to say, if you want to do that refactor then that's fine but please do it as a separate pull request and all in one go.

That said my comment still stands, the comment in the code is hard to parse for me, can you please reword it to be clearer?

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 2 above)
Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: @sestrand says: I agree that lsml code uses camelCase.  but when parsing these files, I think LSML shoudl initially use the exact same name and meaning and spelling and case as PGI source xml... to keep us from getting confused.  There is more I want to change in LSML to get to that start position.  PGI is not consistent in using camelCase in the XML. certainly open to discuss, but it definitely makes it easier to see where in teh code the pgi xml variables end up.

Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: From painful experience from dealing with PGI's UI design and inconsistent, and frequently buggy game XML.

I've made the decision early on for LSML that *emulating PGI's choices is an explicit non-goal*, the goal for LSML is to provide the best experience to the users (and developers), not the same experience. This has served the project well so far (confirmation/survivorship bias be damned :).

For this reason there are deliberate deviations from the way PGI does things, and this also one of the key reasons why the database exists. It isolates all the PGInconsistences to the game parsing part of the code base (which is a little bit of a wild west) and allows the rest of the codebase to work with consistent naming and behaviour.

Like you said, PGI isn't consistent in its own files either. Compare e.g.: `Health`, `projectileHealth`, `projectileclass` and `formation_size`; there is literally every naming scheme known to mankind in just one `WeaponStats` tag. Historically it was even worse, there were some attributes that weren't even consistent in their case between different instances with the same attribute.

Comparatively speaking, a developer will usually spend much more time working with the variables them selves in LSML than comparing them to the game files. In those cases when comparing to the game files has been necessary, the difference is case hasn't proved to be a nuisance, let alone a hindrance.

With all of the above, I do not see a case (pun intended) for changing the naming scheme of these variables in LSML.

File: src/test/java/org/lisoft/lsml/model/item/BallisticWeaponTest.java (hunk 14 above)
Comment (LiSongMWO) [reply src/test/java/org/lisoft/lsml/model/item/BallisticWeaponTest.java:48]: @sestrand says: when you pull the trigger during cooldown, there is no additional time added to the cooldown for that interim shot.  I went into the game and tested against my target self with a stopwatch .  I don't find any additional time... interim shots cant fire before .11 after the first shot, but the cooldown is just the cooldown from completion of the first shot.

Comment (LiSongMWO) [reply src/test/java/org/lisoft/lsml/model/item/BallisticWeaponTest.java:48]: I'm not sure I follow? When you pull down the trigger, you fire 1 round immediately then 2 more rounds each with 0.11 s between them, and the cooldown starts. This is the raw firing period. If you pull the trigger during the cooldown, that's double fire and that only affects eFP, not rFP that's verified in this test (which is admittedly brittle, should use a fake weapon).

> I went into the game and tested against my target self with a stopwatch.

A human with a stop watch isn't accurate enough to measure this without a more thorough testing procedure (which you might have done, but you didn't describe it so I do not know how you tested).

To verify I took a TBR-PRIME that doesn't have any cooldown quirks that affect UACs, I made sure it has no mech skills and equipped 1x C-UAC10 and 207 rounds of ammo. I dropped into testing grounds. I then used a stop watch on my phone and pressed it simulatneously with the trigger button on my mouse that I then held down. I keept holding down the fire button until around 1 minute has passed (this is so that any timing inaccuracies will be divided down) and then I stop the stop watch when I see the next projectile fire after the ammo level has reached 135. In other words, when I stop the timer, the cooldown of the firing period that put us at 135 ammo has just expired so we measure a full firing period at the end. 

The time measured was: 1:05.57. We went from 207 to 135 rounds, resulting in (207 - 135)/3 = 24 fire periods. 
Which results in: 1:05.57 / 24 = 65.57 / 24 = 2.73 seconds per fire period.

However we must correct for the average 0.25 seconds reaction speed of humans to visual stimulus, making it:
1:05.32 / 24 = 65.32 / 24 = 2.72 seconds per fire period.

The game files for C-UAC10 have the following: Cooldown = 2.5, numFiring = 3, volleyDelay = 0.11.
Thus the raw firing period for this weapon, under the current LSML calculations (that are changed in this PR) would be: 2.5 + (3-1)*0.11 = 2.72. This matches exactly with the experimental result, therefore I must conclude that based on this experiment, the current LSML behaviour is correct and the change proposed here is incorrect.

**Comment by sestrand** [comment]
I like the idea of making this abstract.  the weapon class is a superclass
for all actual weapon types, and should never be instantiated.  so abstract
seems like the most proper way to describe it.  I do not mind updating all
of the tests.

But, like you, I do not know how the database will deal with it... so, I'll
have to try it and make sure it all works.

**Comment by LiSongMWO** [comment]
I have fixes ready for the remaining open issues for the next release but they kind of build on some of the concepts discussed here. Realistically after this is submitted I need to retouch one commit a bit and then we can release.

Any chance that you could find some time to whip this PR into shape soon so that we can get a release out ASAP since the parsing has been broken for so long?

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 1 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: I saw this used elsewhere in the code... but I prefer the other way too. done.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 2 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: ok.  I acknowledge your position.  done.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 3 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: ok, I changed some stuff... probably still not what you wanted, but I am not that familiar with how the Docs work.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 5 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: I doubled the variables.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 4 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: removed.

File: src/test/java/org/lisoft/lsml/model/item/WeaponTest.java (hunk 15 above)
Comment (sestrand) [reply src/test/java/org/lisoft/lsml/model/item/WeaponTest.java]: removed.  I was going to test something here then moved it to ammoweapon.

File: src/test/java/org/lisoft/lsml/model/item/WeaponTest.java (hunk 16 above)
Comment (sestrand) [reply src/test/java/org/lisoft/lsml/model/item/WeaponTest.java:105]: A weapon without type only has cooldown.  So, I agree, the test does not really apply at the weapon level, because there is no weapon (other than AMS) that is not either AmmoWeapon or EnergyWeapon.

File: src/test/java/org/lisoft/lsml/model/item/WeaponTest.java (hunk 17 above)
Comment (sestrand) [reply src/test/java/org/lisoft/lsml/model/item/WeaponTest.java]: done.

File: src/test/java/org/lisoft/lsml/model/item/AmmoWeaponTest.java (hunk 19 above)
Comment (sestrand) [reply src/test/java/org/lisoft/lsml/model/item/AmmoWeaponTest.java:133]: Parsing was my worry.  I can add some getRawFiringPeriod in the mix. I did not add UACs or RACs, but otherwise, done.

Comment (LiSongMWO) [reply src/test/java/org/lisoft/lsml/model/item/AmmoWeaponTest.java:133]: Testing parsing is all good, just be mindful that actual values may be changed by PGI in a patch and that could break tests and that causes maintenance work for us (ask me how I know xD). I don't think these particular values will change, but then again I've been wrong on that before. Some times it's better to test for "non default value" rather than specific value. But I think these particular tests will be fine.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 3 above)
Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: Most IDE's will render the JavaDoc format to HTML tooltips with links and inlining of inheritDoc etc. This looks correct to me.

File: src/test/java/org/lisoft/lsml/model/item/BallisticWeaponTest.java [hunk 20]
```diff
@@ -42,10 +42,10 @@ public void testCUAC10() throws Exception {
         final BallisticWeapon cut = (BallisticWeapon) ItemDB.lookup(1206);
 
         assertTrue(cut.getName().contains("C-ULTRA AC/10"));
-        assertEquals(3, cut.getAmmoPerPerShot());
-        assertEquals(10.0, cut.getDamagePerShot(), 0.0001);
+        assertEquals(3, cut.getRoundsPerShot());
+        assertEquals(10.0, cut.getDamagePerShot(), 0.0003);
```
Comment (LiSongMWO) [inline src/test/java/org/lisoft/lsml/model/item/BallisticWeaponTest.java:46]: Why was the tolerance here increased?

File: src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java (hunk 6 above)
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java]: I'm a bit concerned that passing `aRoundsPerShot` to volleysize is not correct for all weapons. E.g. C-UAC/20 has 3 rounds per shot but a volley size of 1. Could you add tests on C-UAC/20 and (C-)LB-10X?

File: src/test/java/org/lisoft/lsml/model/item/BallisticWeaponTest.java (hunk 20 above)
Comment (sestrand) [reply src/test/java/org/lisoft/lsml/model/item/BallisticWeaponTest.java:46]: the test was failing with a result of 10.0002.  so I upped it to .0003 to give it a little margin.

File: src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java (hunk 6 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java]: aRoundsPerShot is not equal to aProjectilesPerRound.   lbx10 fires 10 projectiles per round but only 1 round per shot.  CUAC20 fires 4 projectiles per round but only 1 round per shot.  'aRoundsPerShot' in LSML is 'ammoPerShot' in the PGI file.  'aProjectilesPerRound' in LSML is 'numFiring' in the PGI file.  

the ballistic weapons do not have the 'volleysize' attribute in the PGI file. so I chose aRoundsPerShot over aProjectilesPerRound.  I may be incorrect I will do more testing in the game.

all LSML AmmoWeapons have the 'volleydelay' attribute in the PGI file.

the file is MechWarrior Online\Game\GameData.pak\Libs\Items\Weapons\Weapons.xml.

File: src/test/java/org/lisoft/lsml/model/item/WeaponTest.java (hunk 18 above)
Comment (sestrand) [reply src/test/java/org/lisoft/lsml/model/item/WeaponTest.java]: but if I create and assign in the loop I am spending time to create and release the memory for these two variables.

Comment (sestrand) [reply src/test/java/org/lisoft/lsml/model/item/WeaponTest.java]: so I have set them to 1.0 at initiation and will let the loop then use the values.

Comment (sestrand) [reply src/test/java/org/lisoft/lsml/model/item/WeaponTest.java]: done.

File: src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java (hunk 6 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java]: Well, did more testing.  While it is true that the additional trigger pull on the UAC does not impact the overall cooldown (other than when it jams), the initial volley delay does in fact get added into the firing time.  

so, that really means I should have used aProjectilesPerRound to set volleySize.  

UACs have a volleyDelay of num>0.  LBx has volleyDelay of 0. 

But, the calc for UAC weapons rFP and eFP will be impacted.

File: src/test/java/org/lisoft/lsml/model/item/WeaponTest.java (hunk 18 above)
Comment (LiSongMWO) [reply src/test/java/org/lisoft/lsml/model/item/WeaponTest.java]: This is premature optimization at the cost of readability and the cost of established best practices that are aimed at reducing bugs. 

Unless you have clear evidence that the performance is notably better and the improved performance is _necessary_, please always prefer to follow best practice and declare variables with the smallest scope possible and declared as close to their first use as possible.

In this case, the JVM will not perform any memory allocations on the heap for these varibales as they are basic types (e.g. `int` and `double`) and not objects (c.f. `Integer` and `Double`). You can see this by trying to assign `null` to a `double` vs a `Double`, the compiler will let you know the former isn't possible as it's a basic type. The basic type variables will be allocated on the stack and the compiler will re-use the allocated memory. So you will not see any performance difference caused by hoisting the variables out of the loop. In other words, you're just writing less readable and more error prone code for no benefit.

In addition to that: This is a unit test, it should be written for readability and correctness first and foremost; Performance is a distant third priority here.

File: src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java (hunk 6 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java]: ok, I have corrected the code to convert the ballistic projectiles per shot into something that can be used to determine firing delay.  I believe this is now finally correctly calculated for all types of weapons.  I have added tests for LBX and CUAC

Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java]: That was far worse than I thought.  So I rebuilt a bunch of the setting of volleySize and the creation of a firingDelay variable set at AmmoWeapon initiation.  I dont know of any quirks that shorten that but it would be easy to add if one does exist.

anyway.  I feel pretty good about the firing delay calculation for all weapon types now.. please dig in to see if you find anything I missed.

File: src/test/java/org/lisoft/lsml/model/item/WeaponTest.java (hunk 18 above)
Comment (sestrand) [reply src/test/java/org/lisoft/lsml/model/item/WeaponTest.java]: ah ok.  makes sense.

File: src/test/java/org/lisoft/lsml/model/item/BallisticWeaponTest.java (hunk 20 above)
Comment (LiSongMWO) [reply src/test/java/org/lisoft/lsml/model/item/BallisticWeaponTest.java:46]: I did some digging, seems like something changed subtly in the game files. I don't know what as I cannot go back in time to diff the files between patches... So seems good to me then, I was just worried that something had change in LSML that caused a different output.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java [hunk 21]
```diff
@@ -45,25 +45,36 @@ public class AmmoWeapon extends Weapon {
...
-    private final boolean oneShot;
-
+    private final int volleySize;
+    @XStreamAsAttribute
+    private final int ammoPerShot;
+    @XStreamAsAttribute
+    private final boolean oneShot;    
+    @XStreamAsAttribute
+    private final double firingDelay;
+
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java:55]: Could you move the `volleyDelay` attribute from the `Weapon` class here as well? It no longer make sense without `volleyDelay` so it makes sense that they be together here and I don't see any uses of it in the base class anymore.

**Comment by sestrand** [comment]
Sure. I’ll move the tests too.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java [hunk 22]
```diff
@@ -45,25 +45,36 @@ public class AmmoWeapon extends Weapon {
...
     @XStreamAsAttribute
-    private final boolean oneShot;
-
+    private final int volleySize;
+    @XStreamAsAttribute
+    private final int ammoPerShot;
+    @XStreamAsAttribute
+    private final boolean oneShot;    
+    @XStreamAsAttribute
+    private final double firingDelay;
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: Please don't store the derived value in the class, prefer to calculate it when needed (unless it's notably expensive to compute).

A unit test for a method call can be viewed as a black box with `x + y` bits of input and `z + y` bits of output. Where `x` is the number of total bits in the arguments to the method, `y` is the number of bits stored in the class and `z` is the number of bits in the returned output.

Therefore the number of possible input combinations to the method under test is `2^(x+y)`, meaning that for an exhaustive test suite, that's how many tests you need to write. And massaging the `y` bits into the correct state is very tedious and tends to break good class design. In practice we redue the number of tests by chosing a representative subset of the exhaustive tests focusing on covering all branches, corner cases, happy path and edges of the inputs. 

However, by increasing the input size to the test, the number of tests that are necessary invariably increases. Please try to always reduce the number of variables (the state) in the class to make testing easier. And easier testing results in more testing and less chance of bugs.

In this particular case, if we were to account for tube counts we'd have to remove this constant anyway...

Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: Well that is counter intuitive.  For something that will never change it seems like it should just be calculated one time and be done with it.  I had already added some testing.

What I noticed is that the LSML handler is asking for this value 8 to 10 times for each row of the weapons table.  I cant image how many times this value will be requested on the mech build page.  But I suspect four calls per loaded ballistic or missile weapon.  No it's not a huge calc... but it gets called a lot.

I can put it back into the method.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 21 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java:55]: Sure. I’ll move the tests too.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java [hunk 23]
```diff
@@ -81,19 +92,43 @@ public Ammunition getAmmoType() {
         return ammoType;
     }
 
+    public int getVolleySize() {
+        return volleySize;
+    }
+    
+    public int getAmmoPerShot() {
+        return ammoPerShot;
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java:102]: This will cause the total damage potential calculation to be wrong for C-UACs, I'll explain why, but first: I should document this better but in order to make it easier to reason about, LSML uses the following nomenclature:

* Shot: One trigger pull (for MGs/Flamers/RACs/etc this is one firing period worth of rounds).
* Round: A shot produces 1 or more rounds.
* Projectile: A round has 1 or more projectiles (or in the case of lasers, beams).
* Firing Period: Time between the start time of two consequent shots.

So a shot has rounds and rounds have projectiles. So the damage by one shot is: `damage / projectile * projectiles / rounds * rounds/shot` == `damage/shot`. Firing period is `seconds/shot`. The damage per second is: `(damage / shot) / (seconds / shot)` == `damage / second`. Total damage potential is `damage = shots * damage / shot = total_rounds_of_ammo / (rounds/shot) * damage / shot`.

For example:
LB-10/X: 1 round per shot, 10 projectiles per shot, 1 damage per projectile. 10 damage per shot. 1 ammo (round) consumed per shot.
C-UAC/5: 2 rounds per shot, 1 projectile per shot, 2.5 damage per projectile. 5 damage per shot. 2 ammo (rounds) consumed per shot.
ER PPC: 1 round per shot, 1 projectile per shot, 10 damage per projectile. 10 damage per shot. 0 ammo consumed per shot.

This differs from the nomenclature in the data files which use `numFiring`, `damage`, `ammoPerShot`, `numPerShot`. Because the names in the data file weren't clear on how they were used, I decided on the current naming of these in LSML as it worked for all weapons.

Now, here's the tricky part, MWO isn't consistent in the use of the word "shot". Nor the meaning between different weapon types. For example, IS-LRM 20 has `numFiring=20` and `ammoPerShot=20` which aligns with the LSML meaning of a "shot". But if you look at for example C-UAC/5 it has `numFiring=2` and `ammoPerShot=1`... If you got into the game and load up a C-UAC/5 and shoot once, you'll consume 2 rounds of ammo. So the `ammoPerShot=1` value is not doing what you'd expect... And you can't just take `numFiring * ammoPerShot` because that's wrong for LRMs.

I have yet to find a way to parse the `ammoPerShot` field from the game files in a way that is consistent between all ammo weapons and that actually results in the correct amount of ammo consumed per (LSML) shot. However it turns out that `numFiring` has historically always lined up with the actual number of ammo rounds consumed per shot (as opposed to what `ammoPerShot` actually says), this is why LSML used `numFiring` for `getRoundsPerShot()` which was also used to mean `getAmmoPerShot()` because 1 round (of ammo) = 1 (round of) ammo. In LSML the amount of ammo rounds consumed per shot must be consistent with the LSML meaning of "shot" for the total damage capacity calculations in the info panel to be correct.

I had forgotten about this particular peculiarity of the data files, sorry for not catching this eariler. But you see, this kind of schenanigans is why LSML stays internally consistent rather than emulating whatever PGI does in the data files 😂.

Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java:102]: I know.  I had set it in one spot (just to capture the value) but then started to run into all of the above.  So I felt it was safer to just read it as PGI wrote it... and then LSML would set it appropriately later.  I'll change the creation set ammopershot using numFiring at initiation to be consistent in LSML and with how it actually acts in the game. I dont think getAmmoPerShot is called anywhere (you used getRoundsPerShot for that).  but I feel it would be more robust for future PGI shenanigans if LSML was ready for it.  

I ran into the exact same issues with how they handle the firing delay in ammo weapons.  PGI's inconsistent use of numFiring vs rounds per shot vs volleySize attributes is frustrating.  this could have easily been consistent for all ammo using weapons.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 22 above)
Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: This is another case of premature optimization, but at the cost of testability this time.

It's like 20 instructions to compute this, and on a 10 year old CPU with 10 IPC and 2 GHz, the time spent is around `(20 instructions /10 instructions per clock)/(2E9 clocks per second) = 1ns`. So even if it was done 1000 times per row of the weapons table, it'd still only take a micro second for each row. And the row is only updated when something changes on the mech that affects this attribute.

That said, the JIT optimizer is pretty good and it will do it's magic during runtime, based on what contributes the most to performance. It'll do inlining, constant propagation and common sub-expression elimination etc to avoid re-computing things. Please trust the compiler to do it's job, modern compilers are REALLY good and more often than not, the compiler will produce the same exact machine code for the hand optimized code and the readable code, so always perfer to write the readable/testable code by default.

If there is evidence that the program is too slow or that the JIT optimizer isn't doing a good enough job, then please profile firest and base any optimizations on those profile results.

From my 20 or so years in the industry writing performance critical code, performance is gained by having the right algorithm and through system level design, not by optimizing sub routines. Only in rare circumstances is hand optimizing code worthwhile, and it should only ever be done under the guidance of benchmarking and profiling results. Because otherwise you may spend hours working on something that won't actually affect the runtime of the application, or worst case, make it slower.

File: src/test/java/org/lisoft/lsml/model/item/AmmoWeaponTest.java [hunk 24]
```diff
@@ -104,4 +104,30 @@ public final void testSpreadQuirks() throws Exception {
...
     }
+    
+    @Test
+    public void testGetVolleySize() throws Exception {
+        final AmmoWeapon ac20 = (AmmoWeapon) ItemDB.lookup("AC/20");
+        final AmmoWeapon lrm10 = (AmmoWeapon) ItemDB.lookup("LRM 10");
+        final AmmoWeapon clrm10 = (AmmoWeapon) ItemDB.lookup("C-LRM 10");
+        final AmmoWeapon cuac10 = (AmmoWeapon) ItemDB.lookup("C-ULTRA AC/10");
+        
+        assertEquals(10.0, lrm10.getVolleySize(),0.0);
```
Comment (LiSongMWO) [inline src/test/java/org/lisoft/lsml/model/item/AmmoWeaponTest.java]: `getVolleySize()` returns an `int`, this form of `assertEquals` coerces it to `double` and then compares. Please use `assertEquals(int expected, int actual)` instead of `assertEquals(double expected, double actual, double tolerance)`.

File: src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java (hunk 6 above)
Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/BallisticWeapon.java]: I think this is correct now, bar my separate comment about `ammoPerShot`. I would have passed volley size = 1 through the constructor from the parsing code but this is realistically going to be correct for all ballistic weapons and is heading into YAGNI territory.

Obligatory:
monkeyuser.com

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 23 above)
Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java:102]: Yep, and it is consistent for all ammo weapons in LSML. Welcome to dealing with PGI's consistent inconsistency ;) 

I'm fine with adding `getAmmoPerShot()` if it's used correctly throughout the code base. I'm not sure if `getRoundsPerShot()` is actually used in any other meaning than to get ammo per shot.

File: src/test/java/org/lisoft/lsml/model/item/AmmoWeaponTest.java (hunk 24 above)
Comment (sestrand) [reply src/test/java/org/lisoft/lsml/model/item/AmmoWeaponTest.java]: Sorry, this one is an artifact of my flopping around on how to get this volley size, num rounds, rounds per shot sorted. I'll fix this to be just the int version.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 23 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java:102]: I use getRoundsPer shot to determine the firing delay.  I think that is the correct reason to use it.  But, I'll search around and try to implement ammoPerShot in the right places.  initially, I did not want to mess with what was working for ammunition consumption too much, but the more I have fiddled with firing delay the more I have wanted to go look at ammunition consumption.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 22 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: ok.  I'll move it into the method.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 21 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java:55]: done. But volleydelay is an attribute in laser weapons... all zero (to be more pedantic, some 0.0 and some 0 but all zero), and in the PGI file.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 22 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: done

File: src/test/java/org/lisoft/lsml/model/item/AmmoWeaponTest.java (hunk 24 above)
Comment (sestrand) [reply src/test/java/org/lisoft/lsml/model/item/AmmoWeaponTest.java]: done

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 23 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java:102]: ok, ran into a snag on using getAmmoPerShot. in WeaponSummary we shoud be using ammoPerShot.  but ammoPerShot only exists in the AmmoWeapon Class.  I am not certain how to properly check and then cast the generic weapon from the list to AmmoWeapon without messing up how lasers calculate damage over time. (which in the display should be infinity).

Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java:102]: I would prefer not to undo what I have put in place for this so far... but defer the final use (in the ammo use calculation) of this to a point where I know how to do this right>?

Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java:102]: btw the rest of this is done.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 21 above)
Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java:55]: I don't know of any energy weapon in Battletech that would have volleys. But if there would be one that's added we'd have to move both volley delay and size to the base class... but let's just leave them both in AmmoWeapon for now, it makes more sense.

File: src/main/java/org/lisoft/lsml/model/item/Weapon.java (hunk 8 above)
Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/Weapon.java:64]: Did the github UI hide these comments for you as well? I had to click "load hidden"... don't know why they would hide comments... makes no sense to me.

File: src/main/java/org/lisoft/lsml/view_fx/util/WeaponSummary.java [hunk 25]
```diff
@@ -108,7 +108,7 @@ protected int computeValue() {
                 if (!weapons.isEmpty()) {
                     if (weapons.iterator().next() instanceof AmmoWeapon) {
                         return weapons.stream().map(w -> (AmmoWeapon) w)
-                                      .collect(Collectors.summingInt(AmmoWeapon::getAmmoPerPerShot));
+                                      .collect(Collectors.summingInt(AmmoWeapon::getRoundsPerShot));
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/view_fx/util/WeaponSummary.java:111]: Here you can change to `getAmmoPerShot` directly as `w` is already of type `AmmoWeapon`.

File: src/main/java/org/lisoft/lsml/view_fx/util/WeaponSummary.java [hunk 26]
```diff
@@ -286,7 +286,7 @@ private String getSelectorFor(Item aItem) {
     private boolean shouldCountTubes(Item aItem) {
         if (aItem instanceof MissileWeapon) {
             final MissileWeapon missileWeapon = (MissileWeapon) aItem;
-            return missileWeapon.getAmmoPerPerShot() > 1;
+            return missileWeapon.getRoundsPerShot() > 1;
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/view_fx/util/WeaponSummary.java:289]: This is a `MissileWeapon` which is a sub class of `AmmoWeapon`, you can use `getAmmoPerShot()` directly.

File: src/main/java/org/lisoft/lsml/view_fx/util/WeaponSummary.java [hunk 27]
```diff
@@ -151,7 +151,7 @@ protected double computeValue() {
                 if (weapon.getDamagePerProjectile() == 0) {
                     return 0.0;
                 }
-                return ammoRounds.get() * weapon.getDamagePerShot() / weapon.getAmmoPerPerShot();
+                return ammoRounds.get() * weapon.getDamagePerShot() / weapon.getRoundsPerShot();
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/view_fx/util/WeaponSummary.java]: From memory, this should become:

```suggestion
                if (weapon instanceof AmmoWeapon) {
                    AmmoWeapon ammoWeapon = (AmmoWeapon) weapon;
                    return ammoRounds.get() * ammoWeapon .getDamagePerShot() / ammoWeapon .getAmmoPerShot();
                }
                return Double.POSITIVE_INFINITY;   
```

`ammoRounds.get()` would return `Double.POSITIVE_INFINITY` for non `AmmoWeapon` types so the above computation would result in `Double.POSITIVE_INFINITY * 10 / 1` for ER PPC for example.  I.e. the logic was: energy weapons have infinite ammo so the result becomes infinity.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 23 above)
Comment (LiSongMWO) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java:102]: I commented in WeaponSummary.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java [hunk 28]
```diff
@@ -81,19 +90,49 @@ public Ammunition getAmmoType() {
         return ammoType;
     }
 
+    public int getVolleySize() {
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]:
```suggestion
    protected int getVolleySize() {
```
I don't believe that the user of this class would ever be interested in querying the volley parameters directly. Let's keep the class API as small as possible.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java [hunk 29]
```diff
@@ -81,19 +90,49 @@ public Ammunition getAmmoType() {
...
+        return volleySize;
+    }
+    
+    public double getVolleyDelay() {
```
Comment (LiSongMWO) [inline src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]:
```suggestion
    protected double getVolleyDelay() {
```
See comment above

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 28 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: sounds good to me.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 29 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: yep

File: src/main/java/org/lisoft/lsml/view_fx/util/WeaponSummary.java (hunk 27 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/view_fx/util/WeaponSummary.java]: thanks. I thought there would be an easy way.

Comment (sestrand) [reply src/main/java/org/lisoft/lsml/view_fx/util/WeaponSummary.java]: pushed it.

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 28 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: done

File: src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java (hunk 29 above)
Comment (sestrand) [reply src/main/java/org/lisoft/lsml/model/item/AmmoWeapon.java]: done

**Comment by sestrand** [comment]
nope I did not see this one.

**Comment by sestrand** [comment]
Sure thing.
